### ISSUE TITLE
CustomEvent is not defined

### ISSUE THREAD

**Issue by ha-sante** [teamhanko/hanko#1020]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

- error node_modules\@teamhanko\hanko-frontend-sdk\dist\sdk.modern.js (1:4914) @ eval
- error ReferenceError: CustomEvent is not defined

Using the _"@teamhanko/hanko-frontend-sdk": "^0.8.0",_ in  _"next": "13.4.7",_

### Reproducing the bug

I'd reckon how to reproduce this error is to

1. Init a nextjs app with versioning 13.4.7
2. Install the _"@teamhanko/hanko-frontend-sdk": "^0.8.0",_
3. Init the hanko client provided by the frontend sdk
4. Try to use the passcode feature
5. You will see this error on import and usage.
6. My current impression is that on import it's expecting some core browser features in turn resulting in the error (nextjs 13 has moved to server first which further contributes to this)

### Logs

```Shell
`- error node_modules\@teamhanko\hanko-frontend-sdk\dist\sdk.modern.js (1:4914) @ eval
- error ReferenceError: CustomEvent is not defined
    at __webpack_require__ (direcotorypathtothisfolder\.next\server\webpack-runtime.js:33:43)
    at eval (./src/lib/file.tsx:53:87)
    at (sc_client)/./src/lib/file.tsx (direcotorypathtothisfolder\.next\server\app\(dashboard)\path\page.js:16256:1)
    at __webpack_require__ (direcotorypathtothisfolder\.next\server\webpack-runtime.js:33:43)
    at eval (./src/app/error.tsx:10:68)
    at (sc_client)/./src/app/error.tsx (direcotorypathtothisfolder\.next\server\app\(dashboard)\path\page.js:16201:1)
    at __webpack_require__ (direcotorypathtothisfolder\.next\server\webpack-runtime.js:33:43)
    at JSON.parse (<anonymous>)`
```

### Hanko Version

0.8.0

### OS Hanko Backend

None

### OS

None

### Browser Version

Chrome

### Environment

None

**Comment by ha-sante** [comment]
Will look into this @lfleischmann and report back

**Comment by amjed-ali-k** [comment]
adding `force-dynamic` [Route Segment Config](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config) to the page fixes this issue for me.
```typescript
// layout.tsx | page.tsx | route.ts
export const dynamic = "force-dynamic";
```

**Comment by sojinsamuel** [comment]
> adding `force-dynamic` [Route Segment Config](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config) to the page fixes this issue for me.
> 
> ```ts
> // layout.tsx | page.tsx | route.ts
> export const dynamic = "force-dynamic";
> ```

I tried to add the route config in the root layout, but didnt work. The error in the console is annoying

**Comment by Ashutosh-Bhadauriya** [comment]
Hey @sojinsamuel this issue has been fixed, we need to dynamic import the component where we use it

```js
import dynamic from 'next/dynamic';
const HankoAuth = dynamic(() => import('@/components/HankoAuth'), { ssr: false })

export default function LoginPage() {
 return (
   <HankoAuth />
 );
}
```

**Comment by Ashutosh-Bhadauriya** [comment]
Closing this, as the issue has been addressed.
