### ISSUE TITLE
hanko-elements lang not optional

### ISSUE THREAD

**Issue by like-a-bause** [teamhanko/hanko#548]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

The doc says:
```
lang Currently supported values are "en" for English and "de" for German. If the value is omitted, "en" is used.
```
Tried to update the examples but they wouldn't work with some undefined error.

Providing the lang parameter fixes this. 

### Reproducing the bug

"@teamhanko/hanko-elements": "^0.1.1-alpha"

 <hanko-auth api={api}/>

### Logs

```Shell
elements.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at t.default [as constructor] (elements.js:2:1)
    at y.L [as render] (elements.js:2:1)
    at I (elements.js:2:1)
    at O (elements.js:2:1)
    at I (elements.js:2:1)
    at O (elements.js:2:1)
    at I (elements.js:2:1)
    at O (elements.js:2:1)
    at I (elements.js:2:1)
    at U (elements.js:2:1)
t.default @ elements.js:2
L @ elements.js:2
I @ elements.js:2
O @ elements.js:2
I @ elements.js:2
O @ elements.js:2
I @ elements.js:2
O @ elements.js:2
I @ elements.js:2
U @ elements.js:2
l @ elements.js:2
a @ elements.js:2
(anonymous) @ elements.js:2
(anonymous) @ elements.js:2
a @ elements.js:2
d @ elements.js:2
(anonymous) @ elements.js:2
(anonymous) @ elements.js:2
a @ elements.js:2
t.register @ elements.js:2
(anonymous) @ HankoAuth.tsx:16
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

### Hanko Version

"@teamhanko/hanko-elements": "^0.1.1-alpha"

### OS

None

### Environment

None

**Comment by like-a-bause** [comment]
Fixed by #569
